import 'package:flutter/material.dart';

/// ~ Colors for Green Apple theme
///
/// ~ Original color scheme by CarlosEsco, Jays2Kings and CrepeTF
///
/// ~ M3 colors generated by Material Theme Builder (https:///goo.gle/material-theme-builder-web)
///
/// ~
///
/// ~ Key colors:
///
/// ~ Primary #188140
///
/// ~ Secondary #188140
///
/// ~ Tertiary #D33131
///
/// ~ Neutral #5D5F5B
///

const ColorScheme greenApple = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF7ADB8F),
  onPrimary: Color(0xFF003915),
  primaryContainer: Color(0xFF005322),
  onPrimaryContainer: Color(0xFF96F8A9),
  secondary: Color(0xFF7ADB8F),
  onSecondary: Color(0xFF003915),
  secondaryContainer: Color(0xFF005322),
  onSecondaryContainer: Color(0xFF96F8A9),
  tertiary: Color(0xFFFFB3AA),
  onTertiary: Color(0xFF680006),
  tertiaryContainer: Color(0xFF93000D),
  onTertiaryContainer: Color(0xFFFFDAD5),
  background: Color(0xFF1A1C19),
  onBackground: Color(0xFFE1E3DD),
  surface: Color(0xFF1A1C19),
  onSurface: Color(0xFFE1E3DD),
  surfaceVariant: Color(0xFF414941),
  onSurfaceVariant: Color(0xFFC1C8BE),
  outline: Color(0xFF8B9389),
  onInverseSurface: Color(0xFF1A1C19),
  inverseSurface: Color(0xFFE1E3DD),
  inversePrimary: Color(0xFF006D2F),
  error: Color(0xFFFFFFB4A9),
  onError: Color(0xFFFF680003),
  errorContainer: Color(0xFFFF930006),
  onErrorContainer: Color(0xFFFFFFDAD4),
);
