import 'package:flutter/material.dart';

/// ~ Colors for Midnight Dusk theme
///
/// ~ Original color scheme by CrepeTF
///
/// ~ M3 color scheme generated by Material Theme Builder (https:///goo.gle/material-theme-builder-web)
///
/// ~
///
/// ~ Key colors:
///
/// ~ Primary #F02475
///
/// ~ Secondary #F02475
///
/// ~ Tertiary #7A5733
///
/// ~ Neutral #16151D
///

const ColorScheme midNightDusk = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFF02475),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFBD1C5C),
  onPrimaryContainer: Color(0xFFFFFFFF),
  secondary: Color(0xFFF02475),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFF02475),
  onSecondaryContainer: Color(0xFFFFFFFF),
  tertiary: Color(0xFF55971C),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFF386412),
  onTertiaryContainer: Color(0xFFE5E1E5),
  background: Color(0xFF16151D),
  onBackground: Color(0xFFE5E1E5),
  surface: Color(0xFF16151D),
  onSurface: Color(0xFFE5E1E5),
  surfaceVariant: Color(0xFF524346),
  onSurfaceVariant: Color(0xFFD6C1C4),
  outline: Color(0xFF9F8C8F),
  inverseSurface: Color(0xFF333043),
  onInverseSurface: Color(0xFFFFFFFF),
  inversePrimary: Color(0xFFF02475),
  error: Color(0xFFFFFFB4A9),
  onError: Color(0xFFFF680003),
  errorContainer: Color(0xFFFF930006),
  onErrorContainer: Color(0xFFFFFFDAD4),
);
