import 'package:flutter/material.dart';

/// ~ Colors for Strawberry Daiquiri theme
///
/// ~ Original color scheme by Soitora
///
/// ~ M3 colors generated by Material Theme Builder (https:///goo.gle/material-theme-builder-web)
///
/// ~ Key colors:
///
/// ~ Primary #ED4A65
///
/// ~ Secondary #ED4A65
///
/// ~ Tertiary #775930
///
/// ~ Neutral #655C5C
///

const ColorScheme strawberry = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFB61E40),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFFFDADD),
  onPrimaryContainer: Color(0xFF40000D),
  secondary: Color(0xFFB61E40),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFFFDADD),
  onSecondaryContainer: Color(0xFF40000D),
  tertiary: Color(0xFF775930),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFDDB1),
  onTertiaryContainer: Color(0xFF2A1800),
  background: Color(0xFFFCFCFC),
  onBackground: Color(0xFF201A1A),
  surface: Color(0xFFFCFCFC),
  onSurface: Color(0xFF201A1A),
  surfaceVariant: Color(0xFFF4DDDD),
  onSurfaceVariant: Color(0xFF534344),
  outline: Color(0xFF857374),
  onInverseSurface: Color(0xFFFBEDED),
  inverseSurface: Color(0xFF362F2F),
  inversePrimary: Color(0xFFFFB2B9),
  error: Color(0xFFFFFFB4A9),
  onError: Color(0xFFFF680003),
  errorContainer: Color(0xFFFF930006),
  onErrorContainer: Color(0xFFFFFFDAD4),
);
